from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any, Dict, List

import joblib
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.pipeline_utils import repo_root_from  # noqa: E402


def _inverse_vocab(vocab: Dict[str, int]) -> Dict[int, str]:
    return {idx: token for token, idx in vocab.items()}


def _top_positive_features(
    coef: np.ndarray,
    idf: np.ndarray,
    inv_vocab: Dict[int, str],
    top_k: int,
) -> List[Dict[str, Any]]:
    if coef.ndim != 1:
        raise ValueError("Expected 1D coefficient vector")
    ranked = np.argsort(coef)[::-1]
    out: List[Dict[str, Any]] = []
    for idx in ranked:
        w = float(coef[idx])
        if w <= 0:
            break
        token = inv_vocab.get(int(idx))
        if not token:
            continue
        out.append(
            {
                "token": token,
                "weight": round(w, 8),
                "idf": round(float(idf[idx]), 8),
            }
        )
        if len(out) >= top_k:
            break
    return out


def export_vote_model(model_path: Path, top_k: int) -> Dict[str, Any]:
    pipe = joblib.load(model_path)
    tfidf = pipe.named_steps["tfidf"]
    lr = pipe.named_steps["lr"]
    inv_vocab = _inverse_vocab(tfidf.vocabulary_)
    idf = tfidf.idf_
    payload: Dict[str, Any] = {
        "classes": [str(c) for c in lr.classes_],
        "intercepts": {},
        "top_features": {},
        "meta": {
            "ngram_range": list(tfidf.ngram_range),
            "min_df": int(tfidf.min_df),
            "max_features": int(tfidf.max_features) if tfidf.max_features else None,
        },
    }
    for i, cls in enumerate(lr.classes_):
        cls_name = str(cls)
        payload["intercepts"][cls_name] = round(float(lr.intercept_[i]), 8)
        payload["top_features"][cls_name] = _top_positive_features(lr.coef_[i], idf, inv_vocab, top_k)
    return payload


def export_speech_model(model_path: Path, top_k: int) -> Dict[str, Any]:
    bundle = joblib.load(model_path)
    tfidf = bundle["vectorizer"]
    clf = bundle["classifier"]
    mlb = bundle["label_binarizer"]
    inv_vocab = _inverse_vocab(tfidf.vocabulary_)
    idf = tfidf.idf_

    payload: Dict[str, Any] = {
        "labels": [str(c) for c in mlb.classes_],
        "intercepts": {},
        "top_features": {},
        "meta": {
            "ngram_range": list(tfidf.ngram_range),
            "min_df": int(tfidf.min_df),
            "max_features": int(tfidf.max_features) if tfidf.max_features else None,
        },
    }

    for label, estimator in zip(mlb.classes_, clf.estimators_):
        label_name = str(label)
        coef = estimator.coef_[0]
        payload["intercepts"][label_name] = round(float(estimator.intercept_[0]), 8)
        payload["top_features"][label_name] = _top_positive_features(coef, idf, inv_vocab, top_k)
    return payload


def write_js_module(payload: Dict[str, Any], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "/* Auto-generated by train/export_runtime_model.py. Do not edit manually. */\n"
        f"export const BOTC_RUNTIME_MODEL = {json.dumps(payload, ensure_ascii=False)};\n"
    )
    out_path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export trained sklearn models into lightweight JS runtime features.")
    parser.add_argument("--vote-model", default="models/vote_stance_model.joblib")
    parser.add_argument("--speech-model", default="models/speech_acts_model.joblib")
    parser.add_argument("--out", default="scripts/ml_runtime_model_data.js")
    parser.add_argument("--top-k-vote", type=int, default=180)
    parser.add_argument("--top-k-speech", type=int, default=180)
    args = parser.parse_args()

    root = repo_root_from(__file__)
    vote_model_path = root / args.vote_model
    speech_model_path = root / args.speech_model
    out_path = root / args.out

    if not vote_model_path.exists():
        raise FileNotFoundError(f"Vote model not found: {vote_model_path}")
    if not speech_model_path.exists():
        raise FileNotFoundError(f"Speech model not found: {speech_model_path}")

    payload = {
        "version": "runtime-v1",
        "source_models": {
            "vote": str(Path(args.vote_model).as_posix()),
            "speech": str(Path(args.speech_model).as_posix()),
        },
        "vote_model": export_vote_model(vote_model_path, args.top_k_vote),
        "speech_model": export_speech_model(speech_model_path, args.top_k_speech),
    }
    write_js_module(payload, out_path)
    print(json.dumps({"output": str(out_path), "version": payload["version"]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
