export const ROLE_LOCALIZATION = {
  tb: {
    'washerwoman': { name: '洗衣妇', icon: './assets/roles/tb/washerwoman.png' },
    'librarian': { name: '图书管理员', icon: './assets/roles/tb/librarian.png' },
    'investigator': { name: '调查员', icon: './assets/roles/tb/investigator.png' },
    'chef': { name: '厨师', icon: './assets/roles/tb/chef.png' },
    'empath': { name: '共情者', icon: './assets/roles/tb/empath.png' },
    'fortune-teller': { name: '占卜师', icon: './assets/roles/tb/fortune-teller.png' },
    'undertaker': { name: '送葬者', icon: './assets/roles/tb/undertaker.png' },
    'monk': { name: '僧侣', icon: './assets/roles/tb/monk.png' },
    'ravenkeeper': { name: '守鸦人', icon: './assets/roles/tb/ravenkeeper.png' },
    'virgin': { name: '贞洁者', icon: './assets/roles/tb/virgin.png' },
    'slayer': { name: '猎手', icon: './assets/roles/tb/slayer.png' },
    'soldier': { name: '士兵', icon: './assets/roles/tb/soldier.png' },
    'mayor': { name: '镇长', icon: './assets/roles/tb/mayor.png' },
    'butler': { name: '管家', icon: './assets/roles/tb/butler.png' },
    'drunk': { name: '酒鬼', icon: './assets/roles/tb/drunk.png' },
    'recluse': { name: '陌客', icon: './assets/roles/tb/recluse.png' },
    'saint': { name: '圣徒', icon: './assets/roles/tb/saint.png' },
    'poisoner': { name: '投毒者', icon: './assets/roles/tb/poisoner.png' },
    'spy': { name: '间谍', icon: './assets/roles/tb/spy.png' },
    'scarlet-woman': { name: '红唇女郎', icon: './assets/roles/tb/scarlet-woman.png' },
    'baron': { name: '男爵', icon: './assets/roles/tb/baron.png' },
    'imp': { name: '小恶魔', icon: './assets/roles/tb/imp.png' },
  },
  bmr: {
    'grandmother': { name: '祖母', icon: './assets/roles/bmr/grandmother.png' },
    'sailor': { name: '水手', icon: './assets/roles/bmr/sailor.png' },
    'chambermaid': { name: '侍女', icon: './assets/roles/bmr/chambermaid.png' },
    'exorcist': { name: '驱魔人', icon: './assets/roles/bmr/exorcist.png' },
    'innkeeper': { name: '旅店老板', icon: './assets/roles/bmr/innkeeper.png' },
    'gambler': { name: '赌徒', icon: './assets/roles/bmr/gambler.png' },
    'gossip': { name: '造谣者', icon: './assets/roles/bmr/gossip.png' },
    'courtier': { name: '侍臣', icon: './assets/roles/bmr/courtier.png' },
    'professor': { name: '教授', icon: './assets/roles/bmr/professor.png' },
    'minstrel': { name: '吟游诗人', icon: './assets/roles/bmr/minstrel.png' },
    'tea-lady': { name: '茶艺师', icon: './assets/roles/bmr/tea-lady.png' },
    'pacifist': { name: '和平主义者', icon: './assets/roles/bmr/pacifist.png' },
    'fool': { name: '弄臣', icon: './assets/roles/bmr/fool.png' },
    'tinker': { name: '修补匠', icon: './assets/roles/bmr/tinker.png' },
    'moonchild': { name: '月之子', icon: './assets/roles/bmr/moonchild.png' },
    'goon': { name: '莽夫', icon: './assets/roles/bmr/goon.png' },
    'lunatic': { name: '疯子', icon: './assets/roles/bmr/lunatic.png' },
    'godfather': { name: '教父', icon: './assets/roles/bmr/godfather.png' },
    'devil-s-advocate': { name: '魔鬼代言人', icon: './assets/roles/bmr/devil-s-advocate.png' },
    'assassin': { name: '刺客', icon: './assets/roles/bmr/assassin.png' },
    'mastermind': { name: '主谋', icon: './assets/roles/bmr/mastermind.png' },
    'zombuul': { name: '僵怖', icon: './assets/roles/bmr/zombuul.png' },
    'pukka': { name: '普卡', icon: './assets/roles/bmr/pukka.png' },
    'shabaloth': { name: '沙巴洛斯', icon: './assets/roles/bmr/shabaloth.png' },
    'po': { name: '珀', icon: './assets/roles/bmr/po.png' },
  },
  snv: {
    'clockmaker': { name: '钟表匠', icon: './assets/roles/snv/clockmaker.png' },
    'dreamer': { name: '筑梦师', icon: './assets/roles/snv/dreamer.png' },
    'snake-charmer': { name: '舞蛇人', icon: './assets/roles/snv/snake-charmer.png' },
    'mathematician': { name: '数学家', icon: './assets/roles/snv/mathematician.png' },
    'flowergirl': { name: '卖花女孩', icon: './assets/roles/snv/flowergirl.png' },
    'town-crier': { name: '城镇公告员', icon: './assets/roles/snv/town-crier.png' },
    'oracle': { name: '神谕者', icon: './assets/roles/snv/oracle.png' },
    'savant': { name: '博学者', icon: './assets/roles/snv/savant.png' },
    'seamstress': { name: '女裁缝', icon: './assets/roles/snv/seamstress.png' },
    'philosopher': { name: '哲学家', icon: './assets/roles/snv/philosopher.png' },
    'artist': { name: '艺术家', icon: './assets/roles/snv/artist.png' },
    'juggler': { name: '杂耍艺人', icon: './assets/roles/snv/juggler.png' },
    'sage': { name: '贤者', icon: './assets/roles/snv/sage.png' },
    'mutant': { name: '畸形秀演员', icon: './assets/roles/snv/mutant.png' },
    'sweetheart': { name: '心上人', icon: './assets/roles/snv/sweetheart.png' },
    'barber': { name: '理发师', icon: './assets/roles/snv/barber.png' },
    'klutz': { name: '呆瓜', icon: './assets/roles/snv/klutz.png' },
    'evil-twin': { name: '镜像双子', icon: './assets/roles/snv/evil-twin.png' },
    'witch': { name: '女巫', icon: './assets/roles/snv/witch.png' },
    'cerenovus': { name: '洗脑师', icon: './assets/roles/snv/cerenovus.png' },
    'pit-hag': { name: '麻脸巫婆', icon: './assets/roles/snv/pit-hag.png' },
    'fang-gu': { name: '方古', icon: './assets/roles/snv/fang-gu.png' },
    'vigormortis': { name: '亡骨魔', icon: './assets/roles/snv/vigormortis.png' },
    'no-dashii': { name: '诺-达鲺', icon: './assets/roles/snv/no-dashii.png' },
    'vortox': { name: '涡流', icon: './assets/roles/snv/vortox.png' },
  },
};

